import React from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons, Feather, MaterialCommunityIcons } from '@expo/vector-icons';

export default function FloatingTabBar({ state, descriptors, navigation }) {
  return (
      <View style={styles.wrapper}>
            <View style={styles.tabBar}>
                    <TouchableOpacity
                              style={styles.tabItem}
                                        onPress={() => navigation.navigate('Home')}
                                                >
                                                          <MaterialCommunityIcons
                                                                      name="home-variant"
                                                                                  size={24}
                                                                                              color={state.index === 0 ? '#FF334B' : '#7E7E8A'}
                                                                                                        />
                                                                                                                  <Text style={[styles.tabLabel, state.index === 0 && styles.activeLabel]}>
                                                                                                                              Home
                                                                                                                                        </Text>
                                                                                                                                                </TouchableOpacity>

                                                                                                                                                        <TouchableOpacity
                                                                                                                                                                  style={styles.tabItem}
                                                                                                                                                                            onPress={() => navigation.navigate('Explore')}
                                                                                                                                                                                    >
                                                                                                                                                                                              <Feather
                                                                                                                                                                                                          name="compass"
                                                                                                                                                                                                                      size={22}
                                                                                                                                                                                                                                  color={state.index === 1 ? '#FF334B' : '#7E7E8A'}
                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                      <Text style={[styles.tabLabel, state.index === 1 && styles.activeLabel]}>
                                                                                                                                                                                                                                                                  Explore
                                                                                                                                                                                                                                                                            </Text>
                                                                                                                                                                                                                                                                                    </TouchableOpacity>

                                                                                                                                                                                                                                                                                            {/* Center Search FAB */}
                                                                                                                                                                                                                                                                                                    <TouchableOpacity
                                                                                                                                                                                                                                                                                                              style={styles.centerFab}
                                                                                                                                                                                                                                                                                                                        onPress={() => navigation.navigate('Explore')}
                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                          <LinearGradient colors={['#FF5267', '#D81B34']} style={styles.centerGradient}>
                                                                                                                                                                                                                                                                                                                                                      <Ionicons name="search" size={22} color="#FFF" />
                                                                                                                                                                                                                                                                                                                                                                </LinearGradient>
                                                                                                                                                                                                                                                                                                                                                                        </TouchableOpacity>

                                                                                                                                                                                                                                                                                                                                                                                <TouchableOpacity
                                                                                                                                                                                                                                                                                                                                                                                          style={styles.tabItem}
                                                                                                                                                                                                                                                                                                                                                                                                    onPress={() => navigation.navigate('Details')}
                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                      <Ionicons
                                                                                                                                                                                                                                                                                                                                                                                                                                  name="bookmark-outline"
                                                                                                                                                                                                                                                                                                                                                                                                                                              size={22}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          color={state.index === 2 ? '#FF334B' : '#7E7E8A'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Text style={[styles.tabLabel, state.index === 2 && styles.activeLabel]}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          List
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          wrapper: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              position: 'absolute',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bottom: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      left: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          right: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              tabBar: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  height: 64,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      backgroundColor: '#15151EFA',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: 32,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              flexDirection: 'row',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  justifyContent: 'space-around',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          paddingHorizontal: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderColor: '#22222E',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      elevation: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tabItem: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      tabLabel: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: '#7E7E8A',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      activeLabel: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: '#FF334B',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              centerFab: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  top: -14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      centerGradient: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          width: 48,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              height: 48,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: 24,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              elevation: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  shadowColor: '#FF334B',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      shadowOpacity: 0.4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          shadowRadius: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            