// screens/HomeScreen.js
import React, { useEffect, useState } from "react";
import {
  StyleSheet,
    Text,
      View,
        ScrollView,
          FlatList,
            Image,
              TouchableOpacity,
                ActivityIndicator,
                } from "react-native";
                import { fetchTrendingMovies, fetchTopAnime } from "../services/api";

                const CATEGORIES = ["Action", "Sci-Fi", "Comedy", "Drama", "Animation", "Romance"];

                export default function HomeScreen({ navigation }) {
                  const [trending, setTrending] = useState([]);
                    const [anime, setAnime] = useState([]);
                      const [loading, setLoading] = useState(true);

                        useEffect(() => {
                            async function loadData() {
                                  try {
                                          const [movies, animeList] = await Promise.all([
                                                    fetchTrendingMovies(),
                                                              fetchTopAnime(),
                                                                      ]);
                                                                              setTrending(movies);
                                                                                      setAnime(animeList);
                                                                                            } catch (err) {
                                                                                                    console.error(err);
                                                                                                          } finally {
                                                                                                                  setLoading(false);
                                                                                                                        }
                                                                                                                            }
                                                                                                                                loadData();
                                                                                                                                  }, []);

                                                                                                                                    if (loading) {
                                                                                                                                        return (
                                                                                                                                              <View style={styles.center}>
                                                                                                                                                      <ActivityIndicator size="large" color="#E50914" />
                                                                                                                                                            </View>
                                                                                                                                                                );
                                                                                                                                                                  }

                                                                                                                                                                    const renderCard = ({ item }) => {
                                                                                                                                                                        const imgUri = item.isAnime
                                                                                                                                                                              ? item.poster_path
                                                                                                                                                                                    : `https://image.tmdb.org/t/p/w500${item.poster_path}`;

                                                                                                                                                                                        return (
                                                                                                                                                                                              <TouchableOpacity
                                                                                                                                                                                                      style={styles.card}
                                                                                                                                                                                                              activeOpacity={0.8}
                                                                                                                                                                                                                      onPress={() => navigation.navigate("Details", { item })}
                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                    <Image source={{ uri: imgUri }} style={styles.poster} />
                                                                                                                                                                                                                                            <Text style={styles.cardTitle} numberOfLines={1}>
                                                                                                                                                                                                                                                      {item.title || item.name}
                                                                                                                                                                                                                                                              </Text>
                                                                                                                                                                                                                                                                    </TouchableOpacity>
                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
                                                                                                                                                                                                                                                                                      {/* Category Chips */}
                                                                                                                                                                                                                                                                                            <Text style={styles.sectionTitle}>Categories</Text>
                                                                                                                                                                                                                                                                                                  <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.genreRow}>
                                                                                                                                                                                                                                                                                                          {CATEGORIES.map((cat, idx) => (
                                                                                                                                                                                                                                                                                                                    <View key={idx} style={styles.chip}>
                                                                                                                                                                                                                                                                                                                                <Text style={styles.chipText}>{cat}</Text>
                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                        </ScrollView>

                                                                                                                                                                                                                                                                                                                                                              {/* Trending Movies Carousel */}
                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.sectionTitle}>Trending Movies</Text>
                                                                                                                                                                                                                                                                                                                                                                          <FlatList
                                                                                                                                                                                                                                                                                                                                                                                  data={trending}
                                                                                                                                                                                                                                                                                                                                                                                          keyExtractor={(item) => item.id.toString()}
                                                                                                                                                                                                                                                                                                                                                                                                  renderItem={renderCard}
                                                                                                                                                                                                                                                                                                                                                                                                          horizontal
                                                                                                                                                                                                                                                                                                                                                                                                                  showsHorizontalScrollIndicator={false}
                                                                                                                                                                                                                                                                                                                                                                                                                          contentContainerStyle={styles.listPadding}
                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Top Airing Anime Carousel */}
                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text style={styles.sectionTitle}>Top Airing Anime</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <FlatList
                                                                                                                                                                                                                                                                                                                                                                                                                                                          data={anime}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  keyExtractor={(item) => item.id.toString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          renderItem={renderCard}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  horizontal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          showsHorizontalScrollIndicator={false}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  contentContainerStyle={styles.listPadding}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <View style={{ height: 40 }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      container: { flex: 1, backgroundColor: "#111", paddingTop: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        center: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#111" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          sectionTitle: { color: "#FFF", fontSize: 18, fontWeight: "bold", marginHorizontal: 16, marginTop: 18, marginBottom: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            genreRow: { paddingLeft: 16, marginBottom: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              chip: { backgroundColor: "#222", paddingHorizontal: 14, paddingVertical: 6, borderRadius: 16, marginRight: 8, borderWidth: 1, borderColor: "#333" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                chipText: { color: "#BBB", fontSize: 12, fontWeight: "600" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  listPadding: { paddingLeft: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    card: { width: 130, marginRight: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      poster: { width: 130, height: 190, borderRadius: 6, backgroundColor: "#222" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cardTitle: { color: "#EEE", fontSize: 13, marginTop: 6, fontWeight: "500" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        