// screens/DetailsScreen.js
import React, { useEffect, useState } from "react";
import {
  StyleSheet,
    Text,
      View,
        ScrollView,
          Image,
            TouchableOpacity,
              FlatList,
                ActivityIndicator,
                } from "react-native";
                import { fetchMediaDetails } from "../services/api";

                export default function DetailsScreen({ route, navigation }) {
                  const { item } = route.params;
                    const [details, setDetails] = useState(item);
                      const [loading, setLoading] = useState(!item.isAnime);

                        useEffect(() => {
                            if (!item.isAnime) {
                                  fetchMediaDetails(item.id, item.media_type || "movie")
                                          .then((fullData) => setDetails((prev) => ({ ...prev, ...fullData })))
                                                  .catch(console.error)
                                                          .finally(() => setLoading(false));
                                                              }
                                                                }, [item]);

                                                                  const backdropUri = item.isAnime
                                                                      ? item.backdrop_path
                                                                          : details.backdrop_path
                                                                              ? `https://image.tmdb.org/t/p/w780${details.backdrop_path}`
                                                                                  : `https://image.tmdb.org/t/p/w500${item.poster_path}`;

                                                                                    const genres = details.genres || [];

                                                                                      return (
                                                                                          <ScrollView style={styles.container}>
                                                                                                {/* Banner Backdrop */}
                                                                                                      <View>
                                                                                                              <Image source={{ uri: backdropUri }} style={styles.banner} />
                                                                                                                      <TouchableOpacity
                                                                                                                                style={styles.backButton}
                                                                                                                                          onPress={() => navigation.goBack()}
                                                                                                                                                  >
                                                                                                                                                            <Text style={styles.backText}>←</Text>
                                                                                                                                                                    </TouchableOpacity>
                                                                                                                                                                          </View>

                                                                                                                                                                                <View style={styles.body}>
                                                                                                                                                                                        <Text style={styles.title}>{details.title || details.name}</Text>

                                                                                                                                                                                                {/* Genres */}
                                                                                                                                                                                                        <View style={styles.genres}>
                                                                                                                                                                                                                  {genres.map((g, i) => (
                                                                                                                                                                                                                              <View key={i} style={styles.genreBadge}>
                                                                                                                                                                                                                                            <Text style={styles.genreText}>{g.name || g}</Text>
                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                          </View>

                                                                                                                                                                                                                                                                                  {/* Play Trailer / Stream Button */}
                                                                                                                                                                                                                                                                                          <TouchableOpacity
                                                                                                                                                                                                                                                                                                    style={styles.playButton}
                                                                                                                                                                                                                                                                                                              onPress={() =>
                                                                                                                                                                                                                                                                                                                          navigation.navigate("Player", {
                                                                                                                                                                                                                                                                                                                                        title: details.title || details.name,
                                                                                                                                                                                                                                                                                                                                                      youtubeKey: details.youtubeKey,
                                                                                                                                                                                                                                                                                                                                                                    customUrl: details.trailer_url,
                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                            <Text style={styles.playButtonText}>▶ Play Preview / Trailer</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                    </TouchableOpacity>

                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Synopsis */}
                                                                                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.sectionHeader}>Synopsis</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text style={styles.overview}>{details.overview || "No description available."}</Text>

                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Cast List (Only for TMDB) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            {!item.isAnime && details.cast?.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Text style={styles.sectionHeader}>Top Cast</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <FlatList
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data={details.cast}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          keyExtractor={(c) => c.id.toString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        horizontal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      showsHorizontalScrollIndicator={false}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    renderItem={({ item: c }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <View style={styles.castCard}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          source={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                uri: c.profile_path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? `https://image.tmdb.org/t/p/w185${c.profile_path}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : "https://via.placeholder.com/100x100?text=No+Photo",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={styles.castAvatar}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text style={styles.castName} numberOfLines={1}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {c.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.castRole} numberOfLines={1}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {c.character}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    container: { flex: 1, backgroundColor: "#0D0D0D" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      banner: { width: "100%", height: 240, resizeMode: "cover" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backButton: { position: "absolute", top: 40, left: 16, backgroundColor: "rgba(0,0,0,0.6)", width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          backText: { color: "#FFF", fontSize: 20, fontWeight: "bold" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            body: { padding: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: { color: "#FFF", fontSize: 22, fontWeight: "bold", marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                genres: { flexDirection: "row", flexWrap: "wrap", marginBottom: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  genreBadge: { backgroundColor: "#1F1F1F", borderRadius: 4, paddingHorizontal: 8, paddingVertical: 4, marginRight: 6, marginBottom: 6 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    genreText: { color: "#BBB", fontSize: 11 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      playButton: { backgroundColor: "#E50914", paddingVertical: 12, borderRadius: 6, alignItems: "center", marginBottom: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        playButtonText: { color: "#FFF", fontWeight: "bold", fontSize: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          sectionHeader: { color: "#FFF", fontSize: 16, fontWeight: "700", marginTop: 12, marginBottom: 6 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            overview: { color: "#AAA", fontSize: 13, lineHeight: 20, marginBottom: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              castCard: { width: 80, marginRight: 12, alignItems: "center" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                castAvatar: { width: 70, height: 70, borderRadius: 35, backgroundColor: "#222" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  castName: { color: "#FFF", fontSize: 11, fontWeight: "bold", marginTop: 6, textAlign: "center" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    castRole: { color: "#888", fontSize: 10, textAlign: "center" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    